### ISSUE TITLE
[Bug]: Crash during world gen

### ISSUE THREAD

**Issue by Edle-gans** [dr3ams/Industrial-Village#36]
### General Info

- [X] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6c

### Describe your issue

A bug happened!
[20Jul2024 12:47:33.396] [Thread-80/ERROR] [mezz.jei.library.recipes.PluginManager/]: Recipe registry plugin crashed, it is being disabled: class dev.ftb.mods.ftbxmodcompat.ftbquests.jei.LootCrateRecipeManagerPlugin
java.lang.IllegalStateException: A JEI API method is being called by another mod from the wrong thread:
Thread[Thread-80,10,main]
It must be called on the main thread by using Minecraft.addScheduledTask.
	at mezz.jei.common.util.ErrorUtil.assertMainThread(ErrorUtil.java:148) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at mezz.jei.library.ingredients.IngredientManager.addIngredientsAtRuntime(IngredientManager.java:77) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.jei.LootCrateRecipeManagerPlugin.lambda$new$1(LootCrateRecipeManagerPlugin.java:27) ~[ftb-xmod-compat-forge-2.1.1.jar%23518!/:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedLootCrateCache.rebuildWrappedLootCrateCache(WrappedLootCrateCache.java:52) ~[ftb-xmod-compat-forge-2.1.1.jar%23518!/:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedLootCrateCache.getWrappedLootCrates(WrappedLootCrateCache.java:30) ~[ftb-xmod-compat-forge-2.1.1.jar%23518!/:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.jei.LootCrateRecipeManagerPlugin.getRecipes(LootCrateRecipeManagerPlugin.java:71) ~[ftb-xmod-compat-forge-2.1.1.jar%23518!/:?]
	at mezz.jei.library.recipes.PluginManager.lambda$getRecipes$5(PluginManager.java:80) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at mezz.jei.library.recipes.PluginManager.safeCallPlugin(PluginManager.java:96) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at mezz.jei.library.recipes.PluginManager.getRecipes(PluginManager.java:78) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at mezz.jei.library.recipes.PluginManager.getPluginRecipeStream(PluginManager.java:66) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at mezz.jei.library.recipes.PluginManager.lambda$getRecipes$0(PluginManager.java:36) ~[jei-1.20.1-forge-15.3.0.8.jar%23538!/:15.3.0.8]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:259) ~[emi-1.1.10+1.20.1+forge.jar%23492!/:?]
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185) ~[emi-1.1.10+1.20.1+forge.jar%23492!/:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

### Additional Information

[2024-07-20-1.log.gz](https://github.com/user-attachments/files/16321132/2024-07-20-1.log.gz)
[crash-2024-07-20_12.47.37
[debug-1.log.gz](https://github.com/user-attachments/files/16321135/debug-1.log.gz)
-client.txt](https://github.com/user-attachments/files/16321134/crash-2024-07-20_12.47.37-client.txt)

**Comment by Gunner76th** [comment]
Please provide the actual text files for the crash report,  debug files. Log.gz are archive files that cannot be opened on mobile platforms. Also please include the file named latest that's in the logs folder.

**Comment by Gunner76th** [comment]
Also what is any changes to the modpack have you made?
